### PR TITLE
Script modifications for linux

### PR DESCRIPTION
**Pull request by bsmith94**
Fix for #11 

These revisions allow killrvideo to launch on Centos 7. I also added a command-line option to setup_docker.sh and create-environment.sh that allows the user to specify the loopback IP, which also avoids creating the loopback alias.

```
./setup_docker -l 192.168.5.10
```

Intra-container port access was being blocked by firewalld. I'm not a docker wiz, so I turned off firewalld and things are working, for the most part.

Video suggestions are not working. Not sure why.

### CODE REVIEW

**Comment by bsmith94** [comment]
I also pulled in jstafford's pull request into my fork, as you can see. Hope that doesn't confuse things.

**Comment by SonicDMG** [comment]
"Video suggestions are not working. Not sure why."  If you are referring to the recommendations section it is simply not implemented in the node.js version.  We currently only have Graph support in the Java version with DSL's.  This is on the plate, but something we haven't gotten to yet.

**Comment by jeffreyscarpenter** [comment]
I tested and merged in the prior pull request separately.
This pull request mostly affects the create-environment.sh script, which gets pulled in from killrvideo-docker-common repo via a subtree pull. I made a similar (but simpler) change to the script in killrvideo-docker-common and then executed a subtree pull in dependent repos (-node, -java, -generator, -web).

**Comment by jeffreyscarpenter** [comment]
Hopefully that all makes sense @bsmith94. Thanks and let us know if you have more feedback.

**Pull request closed without merging**
